### PR TITLE
(TWILL-111) support MapR file system (including examples)

### PR DESCRIPTION
**Pull request by tongqqiu**
- add maven profile to support mapr file system. 
- minor change in the code to accept "maprfs" schema.
- verified on mapr hadoop 2.4.1 clustering environment.

### CODE REVIEW

**Comment by chtyim** [comment]
the changes LGTM. Can you update the `.travel.yml` to add a run for the mapr profile?

**Comment by tongqqiu** [comment]
Need more work on minicluster, still have some issues

**Comment by tongqqiu** [comment]
MapR said they doesn't support MiniDFSCluster, making most of yarn related tests failed. The only thing I can do is to skip the related tests on the mapR profile. It is working on a cluster, but it is bad that it cannot be run on unit tests.

Here is the mapr's response. 
 http://answers.mapr.com/answers/162098/view.html

I also notice that testDeadlock on ZkClientTest failed on all profiles, not just my mapr profile. I guess that is related another ticket Twill-110.

**Comment by chtyim** [comment]
The deadlock test shouldn't be ignore. What JDK version are you using?

**Comment by tongqqiu** [comment]
revert the "ingore dedelock test", since it works on travis CI https://travis-ci.org/apache/incubator-twill/builds/47527433

**Comment by chtyim** [comment]
Changes LGTM. Merging into master.

**Comment by chtyim** [comment]
Merged. Please close this PR. Thanks.

**Pull request closed without merging**
