### PR TITLE
TWILL-126 Use Travis CI container-based testing

### PR DESCRIPTION
**Pull request by wolf31o2**
This updates Twill to use the Travis CI container-based infrastructure and S3 caching for Maven-downloaded resources. The `.travis.yml` has been validated using [Travis Lint](http://lint.travis-ci.org/) and is valid.

### CODE REVIEW

**Comment by chtyim** [comment]
Changes LGTM. Will wait for travis build then merge.

**Comment by wolf31o2** [comment]
It looks like the Travis builds hung. They never even launched. I don't have access to restart them. Can you do so? If they don't work, after that. I'll go back to the drawing board on this. I've done this with other projects, both Ruby and Java, with no issues, so I am hoping it's just a Travis glitch.

**Comment by wolf31o2** [comment]
Travis finally scheduled these. Builds passed.

**Comment by chtyim** [comment]
Merged and pushed to master. Please close this PR. Thanks for the contribution.

**Comment by wolf31o2** [comment]
Closing.

**Pull request closed without merging**
