### PR TITLE
(TWILL-160) Don’t create parent directory when getting InputStream from a LocalLocation

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Comment by poornachandra** [comment]
LGTM

**Comment by hsaputra** [comment]
Hi Terence,

Do you know why parent directory was created before? The JIRA did not have information about it.

**Comment by chtyim** [comment]
@hsaputra I believe it just a bug. The usual convention of creating InputStream from file shouldn't create anything in the FS if the file doesn't exist.

**Comment by hsaputra** [comment]
:+1: 

LGTM

**Pull request closed without merging**
