### PR TITLE
Upgrade version to 0.6

### PR DESCRIPTION
**Pull request by killerwhile**

### CODE REVIEW

**Comment by chtyim** [comment]
LGTM.

**Comment by hsaputra** [comment]
LGTM
+1

**Comment by hsaputra** [comment]
I have filed issue to update the how to contribute page to describe how to update the project website:
https://issues.apache.org/jira/browse/TWILL-146

**Comment by hsaputra** [comment]
Thanks for the patch @killerwhile . Seemed like the PR did not close propertly. Would you mind closing this one since the PR already merged? Thx

**Pull request closed without merging**
